# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'LocalMarketplace' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LocalMarketplace
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'

  target 'LocalMarketplaceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LocalMarketplaceUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
